### ISSUE TITLE
Silent install (Windows 10) is broken

### ISSUE THREAD

**Issue by pikachuprof** [GEANT/CAT#119] opened 2018-09-10 13:22 UTC
# Issue type
- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [x] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description
the silent installation is defect, there is still a (unnecessary) popup that asks for a "OK" that it will install Software

## How to reproduce issue
Run the installer from the command line / powershell or client-management with the parameter "/S" for the silent installation

## Detail of issue

A dialog box informs the user about the installation of additional Software (GÉANTLink) that may requires administrative privileges. This box still shows up in Silent installation. The easiest way of fixing this is just Dropping this box completely as it seems unnecessary in the first place...

This issue/bug blocks the use of the installer in client-management or MDT or similar tools.

## Quirky workaround:

Extract GÉANTLink from the Package install it and run the installer afterwards. Then the dialog does not show up 'cause no additional software is installed ;-) 

## Other quirks with silent installation

- the credentials Window for users states that "wrong credentials" had been entered (cosmetical error, because it works as intended)

- if you provide full-chain and not only root-CA you get multiple prompts for each chain element one, and only one of which is working (random)

**Comment by Lukas-UAUX** [comment] 2018-09-28 09:14
If you provide full-chain you get multiple **credential** prompts for each chain element one

**Comment by twoln** [comment] 2018-09-28 09:18
I will try to investigate that, but yesterday I could not make this happen. Can we continue over email (twoln@umk.pl)?

**Comment by twoln** [comment] 2018-09-28 11:19
I have hun another test and the same result. I only get a prompt for the ROOT certificate, not for the intermediate. Did this in the silent mode and I am quite sure that none of the certs was in the Windows store. Could it be that in fact you have been installing two roots?

**Comment by Lukas-UAUX** [comment] 2018-09-28 12:15
i found out that this issue may be fixed already because a college had contact with the DFN before about this issue, but I am not sure. I can not test it as I am not the "head" CAT administrator of our University, (it would be cool if there were a dummy/testing version of CAT ;-) )

As far as I know we only had set the full chain of one cert and the issue got away after we changed to use only root (as it should be anyway if the server can provide fullchain).

**Comment by twoln** [comment] 2018-09-28 13:45
We have the test site at https://cat-test.eduroam.org/beta this is where we have the current beta release installed.

**Comment by twoln** [comment] 2018-10-09 14:05
Is it OK to close this issue? If not then we should return to it.

**Comment by Lukas-UAUX** [comment] 2018-10-09 14:36
the main issue, the broken silent installation, is still there, only the little quirk with the full-chain could already be fixed (can not check)

**Comment by twoln** [comment] 2018-12-27 21:38
Did you test the installers recently? There was an update that also addressed your issue.

If you still see the problem then please contact me be email at twoln@umk.pl, I would need to get some details to reproduce the problem.

Tomasz

**Comment by ikreb7** [comment] 2020-08-18 15:56
I think this issue could be closed.

**Comment by twoln** [comment] 2020-08-31 13:27
With no more responses, I am closing the issue.

**Closed by twoln** 2020-08-31 13:27 UTC
