### ISSUE TITLE
Adding CA to RADIUS/EAP profile in CAT admin is broken [BLOCKER]

### ISSUE THREAD

**Issue by jirutka** [GEANT/CAT#216] opened 2021-03-09 17:06 UTC
# Issue type

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [x] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description

Adding CA to RADIUS/EAP profile in CAT admin is broken.

I need to change the CA file in the EAP profile, but it doesn’t work. I’ve tried edit the existing profile, create a new one, upload a file with a single PEM, full chain, chain without root, use file upload and URL… but everything leads to the same error result. 

The result is that our profile is inactive, our users cannot use CAT now and there’s nothing we can do about it. 
I posted this issue on cat-users@lists.geant.org yesterday, but still no answer. 

## How to reproduce issue

1. On https://cat.eduroam.org/admin/overview_idp.php click on [Edit] in the profile box.
2. In “EAP Details for this profile”:
2.1 remove existing CA Certificate File using [-] button,
2.2 click on [Add new option], select “CA Certificate URL” and paste https://pki.cesnet.cz/_media/certs/usertrust_rsa_certification_authority.pem.
3. Click on [Save data] and you will get the result page with:

        Supported EAP Type: PEAP-MSCHAPv2 is missing required information CA Certificate File !
        The EAP type was added to the profile, but you need to complete the missing information before we can produce installers for you.

4. Click on [Continue to dashboard], you will see the following text in the profile box: “EAP-MSCHAPv2 Information needed! CA Certificate File”.
5. Click on [Edit] again, you will see that the certification file was actually correctly parsed, but there’s (I) in a blue circle without any alt text or anything next to the [-] button and the text box with the parsed certificate DN:

        C=US
        ST=New Jersey
        L=Jersey City
        O=The USERTRUST Network
        CN=USERTrust RSA Certification Authority

**Comment by twoln** [comment] 2021-03-09 17:42
You are pointing to an itermediate certificate not root, which is requied to configure EAP supplicants. If you provide a root it will work.
Hoverer we know that there actually is a bug in this place. The certificate gets saved an it is reported on the summary, but still there is a misleading warning at the bottom of the summary. This will be corrected in an update soon.

**Comment by jirutka** [comment] 2021-03-09 18:22
Thank you for the quick reply!

You are right, I’ve added [root certificate](https://pki.cesnet.cz/_media/certs/aaa_certificate_services.pem) and it finally works. However, I’m totally confused now because I’m quite sure that yesterday I tried to use even [full chain](https://pki.cesnet.cz/_media/certs/aaa_certificate_services.pem), including the root CA, and it didn’t work. I probably decided that it doesn’t work according to the faulty error message on the result page, but I don’t believe I would overlook the OK status on the overview page… I don’t remember if I tried just the root CA alone and why I’ve been convinced that the USERTrust RSA Certification Authority certificate (intermediate) should be used. I was under a lot of stress yesterday, so I somehow messed it up in my head.

However, the error messages in the CAT admin interface was not helpful at all, it’s incredibly confusing! Also, the (I) and (R) icons are very bad UI – they should have at least a `title` attribute with description. I even looked into HTML if there’s any sort of information about what does this (I) icon mean. If I had known that it stands for “Intermediate”, it would give me the needed hint. And for the last, there’s no link to the documentation – I found it just a while ago by accident when looking for something else.

**Comment by twoln** [comment] 2021-03-09 19:32
I am not sure that CAT will allow you to pull a full chain in a single file it could be that depending on the order of certs in the file it will pick up the root or bot (but I the would require to be tested/verified in the code).
I am sure we will take you UI comments into account.

**Comment by restena-sw** [comment] 2021-04-02 06:28
Regarding the link to the documentation: it's right there, in plain sight.
![Screenshot_20210402_082711](https://user-images.githubusercontent.com/6346943/113387795-4c050000-938d-11eb-972f-e55031096a70.png)

(the last line of the "Personal Overview Page")

It used to be near the top, before all the core information, but a UI expert review team told us that it's best to position it at the end, so it changed its place.

**Comment by restena-sw** [comment] 2021-04-02 06:42
I just verified that upload a single .pem file with two CAs inside will add both CAs as intended. The bug about reporting incomplete CA data even though it was uploaded at the very same moment is confirmed gone (we installed a hotfix to that effect a few weeks ago already).

This leaves nothing to do in this PR, closing it.

**Closed by restena-sw** 2021-04-02 06:42 UTC
