### ISSUE TITLE
Proxy settings causing network access issues on Mac

### ISSUE THREAD

**Issue by DanSheps** [GEANT/CAT#228] opened 2021-11-26 19:24 UTC
# Issue type

- [X] Defect - Unexpected behaviour (obvious or has been verified by a project member).

# Defect/Feature description

On certain mac systems with certain external settings, the Proxy settings that are pushed by eduroam result in failures to properly connect or access the network.

## How to reproduce issue

Unfortunately there may be additional steps missing as we cannot always tell what settings users have at home or non-eduroam networks.

* Download any eduroam profile
* Install on a mac device
 
## Detail of issue

The eduroam CAT profile generator pushes out the following profile settings:

```xml
				<key>ProxyPACFallbackAllowed</key>
				<true />
				<key>ProxyType</key>
				<string>Auto</string>
```

This appears, in certain circumstances, to cause issues with end-user devices (not always on the institution's network, could be on corporate networks or on home networks).  This results in certain services (notably updates) or all services failing to work.  This seems to be a result of the specific DNS configuration of the location as it only appears to fail when a query to wpad.lan is sent and "REFUSED" vs returning "NXDOMAIN"

Issue is discussed here: https://lists.geant.org/sympa/arc/cat-users/2021-11/msg00000.html with 3 different institutions experiencing the issue and confirming removal of proxy settings resolve it.

In the University of Winnipeg's instance, the issue was with the end-users home network and not with the institution's network and only impacted updates on the system itself.

The specific setup of the end user was as follows:

* Apple MacOS Big Sur
* Nest WiFi
* Local resolver for Nest router

**Comment by restena-sw** [comment] 2021-11-29 11:34
Thank you for the investigation on the exact circumstances that trigger the behaviour you saw. We occasionally hear about this issue, but only very seldomly with enough technical detail to pinpoint a concrete root cause.

While I see these very seldom failures on arguably misconfigured individual networks, I don't think the mobileconfig installers can be changed in any way that would make the profiles _more_ compatible.

That is because eduroam SPs are allowed to deploy network proxies, so long as those proxies are transparent - i.e. do not require manual configuration. This is a somewhat popular option for deployments. The configuration files we generate have to take this deployment choice into account.

So, while setting Proxy to Off may very help connectivity in the (few) misconfigured networks that don't enable proxy autoconfig, it would at the same time break eduroam for those users on all eduroam hotspots that deploy a supported proxy configuration.

(and we don't have to discuss setting this option to the third of three available options "manual" for obvious reasons)

So, while I appreciate the imperfection: I don't see any options for improving the situation. Other than not using network equipment/configurations that break proxy auto-detection.

**Comment by restena-sw** [comment] 2021-12-07 15:14
I have added a section about proxy settings for eduroam SP network operators on the wiki: https://wiki.geant.org/display/H2eduroam/eduroam+SP

Since there is no better way of handling proxy config than auto-detect, closing the issue for now.

**Closed by restena-sw** 2021-12-07 15:14 UTC
