### ISSUE TITLE
[Linux Installer] Doesn't fall back to kdialog, if zenity does not work

### ISSUE THREAD

**Issue by xuiqzy** [GEANT/CAT#154] opened 2019-07-03 10:19 UTC
# Issue type

- [ x ] Defect - Unexpected behaviour (obvious or has been verified by a project member).

# Defect/Feature description

## How to reproduce issue
Run Linux installer on newest (2019-07-03) Arch Linux with zenity 3.32.0-1 and kdialog 19.04.2-1 installed.
 
## Detail of issue

No dialog is displayed and installer exits with exit code 1.
When manually setting kdialog as graphics interface, everything works.
Obviously zenity should work (and manually testing it on the command line works!), but if it does not for some reason and the dialog creation returns false, it shoud switch to kdialog, if that is available.
At least an error message that the dialog creation with <current graphics framework> failed woud be extremely helpful :)

Thanks for providing this setup tool and let me know, if I can provide further details to help fix the issue!

**Comment by ikreb7** [comment] 2019-11-06 09:38
Hello,

could you call the script please with the parameter ``--debug`` again, please?

**Comment by chippisc** [comment] 2019-11-27 11:12
Hello,
i have a similar issue - script does not work at all - no matter if kdialog is installed or not. I use Arch with Plasma. Quits after starting constructor without showing any error or dialog-box.
```
eduroam-linux-DHBSDS.py:148: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  system = platform.linux_distribution()
DEBUG:['arch', 'Arch', 'kde']
DEBUG:Calling InstallerData
DEBUG:starting constructor
```
I do not have any Python experience so I am sorry to not offer more information - if there is anything I can add i would be happy to help.

**Comment by ikreb7** [comment] 2020-08-18 15:56
Hallo @chippisc, 

thanks for your offer and sorry for the very very late reply. Do you have zenity installed or only kdialog? For which institution do you use the installer? Maybe I could send you a fixed installer version for tests.

**Comment by chippisc** [comment] 2020-08-18 16:28
@ikreb7 hey thanks for answering!
I am sorry, I managed to set up the connection manually and as it has been a while I do not remember exactly what problems I encountered and what steps I tried - I think I tried zenity but not sure :/ The institution was Duale Hochschule baden Württemberg (DHBW)... And I think they configured some strange stuff so maybe that is why it did not work correctly.

**Comment by ikreb7** [comment] 2020-08-18 19:47
The installer seems to be unchanged from your institution. So I think the error still exists but will be difficult to reproduce. 

I will add more log information and hope we will come closer if the next person complains.

But thanks for the very fast reply!

**Comment by sdasda7777** [comment] 2024-09-27 14:57
Hi, could you please check if the issue still persists? There have been some changes lately.

**Comment by chippisc** [comment] 2024-09-27 15:10
> Hi, could you please check if the issue still persists? There have been some changes lately.

Very sorry, but I did change computer and distribution so no chance to retest.

If I am the only one the installer failed for maybe it's fine? After all arch installations can be very custom so probably it was an edge case from the beginning.

**Closed** 2024-10-11 11:03 UTC
