### ISSUE TITLE
Universidad Rey Juan Carlos: Config Profile on Android doesn't work.

### ISSUE THREAD

**Issue by javich-dev** [GEANT/CAT#155] opened 2019-09-03 11:25 UTC
![Screenshot_2019-08-02-12-00-46](https://user-images.githubusercontent.com/54804218/64169228-90e15180-ce4d-11e9-8a2c-3e2efc0d43a8.png)
# Issue type
- Questions about the eduroamCAT or its usage should be sent to the [users mailing list](https://lists.geant.org/sympa/info/cat-users).

- [ ] Defect - Crash/memory corruption.
- [ ] Defect - Non-compliance with a standards document or incorrect OS API usage.
- [X ] Defect - Unexpected behaviour (obvious or has been verified by a project member).
- [ ] New feature request.

# Defect/Feature description
Our profile on Android doesn't work fine.

## How to reproduce issue
When yo search our University profile on app EduroamCAT you can't install it.

*remove this section if this is a new feature request*
 
## Detail of issue
When yo search our University profile on app EduroamCAT you can't install it.

*remove this section if this is a new feature request*

```text
**copy/paste evidence or feature request here. No links to 3rd party sites.
```

**Comment by javich-dev** [comment] 2019-09-03 11:29
**APP:** EduroamCAT
**SO:** Android 7
**Devices:** 

- Huawei Media Pad M3
- Huawei P10

**Comment by restena-sw** [comment] 2019-09-06 07:12
I have just installed the Rey Juan Carlos profile on a Samsung Galaxy S6 with Android 7. It downloaded and installed just fine.
Given that it's the same Android version I suspect that this is something rather vendor-specific for Huawei; in contrast it does not look like the configuration file as sent from the server-side of CAT is in any way incorrect.
I see that you have opened a mirrored issue in the CAT-Android repository. Since the issue is app-side and only on specific devices, that is actually the better place to raise this.

Consequently, I'm closing this issue here, and will leave the one on the CAT-Android repository open for the developer to take a look.

**Closed by restena-sw** 2019-09-06 07:12 UTC

**Comment by javich-dev** [comment] 2019-09-07 07:56
Thank you restena-sw for your help.
We'll try on others smartphones.

javich.
